### ISSUE TITLE
Class not found exception in BookShelf when doing //copy or //paste in AyncWorldEdit

### ISSUE THREAD

**Issue by mattc4t** [Shrek5InTheatres2019/BookShelf#4]
I am running BookShelf on a Spigot 1.14.4 server with numerous other plugins, including AsyncWorldEdit. Each time one of our staff does //copy or //paste (and a few other operations in AsyncWorldEdit), we are getting a stack trace -- where at the bottom shows a missing class definition error for handling WorldEdit events:

_**Caused by: java.lang.NoClassDefFoundError: me/MitchT/BookShelf/ExternalPlugins/WorldEditLogger
	at me.MitchT.BookShelf.ExternalPlugins.WorldEditHandler.wrapForLogging(WorldEditHandler.java:42) ~[?:?]

Older versions of Bookshelf played fine with WorldEdit/AsyncWorldEdit - so I'm not sure why/how Bookshelf would be interacting with it.  Here is the full stack trace:
 

[00:41:18] [Server thread/ERROR]: Could not dispatch event: org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$WrapEditSessionEvent@4947759 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:105) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:69) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:499) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.EditSession.wrapExtent(EditSession.java:266) ~[?:?]
	at com.sk89q.worldedit.EditSession.<init>(EditSession.java:237) ~[?:?]
	at com.sk89q.worldedit.AweEditSession.<init>(AweEditSession.java:66) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.ThreadSafeEditSession.<init>(ThreadSafeEditSession.java:250) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSession.<init>(AsyncEditSession.java:115) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.AsyncEditSessionFactory.getEditSession(AsyncEditSessionFactory.java:133) ~[?:?]
	at com.sk89q.worldedit.LocalSession.createEditSession(LocalSession.java:898) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.WrappedLocalSession.createEditSession(WrappedLocalSession.java:151) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$null$4(PlatformCommandManager.java:244) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_222]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$registerAlwaysInjectedValues$5(PlatformCommandManager.java:243) ~[?:?]
	at org.enginehub.piston.inject.MapBackedValueStore.lambda$injectedValue$0(MapBackedValueStore.java:56) ~[?:?]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_222]
	at org.enginehub.piston.inject.MapBackedValueStore.injectedValue(MapBackedValueStore.java:56) ~[?:?]
	at org.enginehub.piston.inject.MergedValueAccess.lambda$injectedValue$0(MergedValueAccess.java:54) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_222]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_222]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_222]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_222]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_222]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_222]
	at org.enginehub.piston.inject.MergedValueAccess.injectedValue(MergedValueAccess.java:57) ~[?:?]
	at org.enginehub.piston.inject.MemoizingValueAccess.injectedValue(MemoizingValueAccess.java:84) ~[?:?]
	at org.enginehub.piston.impl.CommandParametersImpl.injectedValue(CommandParametersImpl.java:109) ~[?:?]
	at org.enginehub.piston.inject.InjectedValueAccess.injectedValue(InjectedValueAccess.java:44) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration.editSession(RegionCommandsRegistration.java:730) ~[?:?]
	at com.sk89q.worldedit.command.RegionCommandsRegistration._set(RegionCommandsRegistration.java:399) ~[?:?]
	at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[?:?]
	at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:471) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_dispatch(EventBus.java:193) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.dispatch(EventBusWrapper.java:105) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.nonwrapped_post(EventBus.java:181) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.util.eventbus.EventBusWrapper.post(EventBusWrapper.java:69) ~[?:?]
	at org.primesoft.asyncworldedit.worldedit.CancelabeEditSession$EventBusWrapESEvent.post(CancelabeEditSession.java:499) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java) ~[?:?]
	at com.sk89q.worldedit.bukkit.WorldEditPlugin.onCommand(WorldEditPlugin.java:341) ~[?:?]
	at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:55) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:710) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1641) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1481) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:909) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:902) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:885) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:819) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1122.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 71 more
_**Caused by: java.lang.NoClassDefFoundError: me/MitchT/BookShelf/ExternalPlugins/WorldEditLogger
	at me.MitchT.BookShelf.ExternalPlugins.WorldEditHandler.wrapForLogging(WorldEditHandler.java:42) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1122.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[?:?]
	at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
	... 71 more**_

**Comment by Shrek5InTheatres2019** [comment]
The API has changed a bit in newer worldedit versions, and as the sole developer for the plugin, i can only work on one bug at a time. I'll make sure this is fixed ASAP though

**Comment by mattc4t** [comment]
> 
> 
> The API has changed a bit in newer worldedit versions, and as the sole developer for the plugin, i can only work on one bug at a time. I'll make sure this is fixed ASAP though

Thanks for carrying Bookshelf forward!  WorldEdit has seen a bit of change to support Minecraft 1.14.x.
